### ISSUE TITLE
Issue with Outer Background Color

### ISSUE THREAD

**Issue by mbregg1** [stefanheule/obsidian#15]
At some point tonight on my Pebble Time Steel, the Outer Background Color became "stuck" on yellow, no matter what I change it to.  I can change any of the other colors properly.

I've tried uninstalling/reinstalling the watchface and rebooting the PTS, but it doesn't seem to help.  Any ideas?

**Comment by mbregg1** [comment]
Ugh, nevermind, it was the Low Battery background color.

**Comment by stefanheule** [comment]
No worries, and thanks for taking the time to open a ticket, even if it ended up not being a bug.  I sometimes wonder if I should change the defaults, you are not the first person to be confused by this feature.  In any case, if you don't like the background that's changing, then you can set the background color for the low battery version to be the same as the normal background.
