### ISSUE TITLE
Weather data is lost...

### ISSUE THREAD

**Issue by WJCFerguson** [stefanheule/obsidian#20]
Perhaps this is just my setup in some way - but for a couple of weeks now I've lost all weather data on Obsidian.  

I've tried changing weather providers, unistalling/reinstalling etc., but no joy.  I have been using Weather Underground with an API key, but even switching back to Open Weathermap I get nothing.  Other (inferior) faces get their weather data.

Is it just me?  Or has something changed?  I'm on Android 8.0.0.

I hope you're still using and supporting this face (it's head and shoulders above the rest, IMO) though if it is just a problem in my setup I suppose I'm on my own... :).  Any debugging pointers gratefully received.

**Comment by stefanheule** [comment]
I'm not using the watchface any longer (I've moved on to my second watch face called graphite), but if I can I try to keep this one running, too.

I just installed Obsidian again to see if I get the same problem, but weather with all three providers seems to work for me.  I'm also on Android 8.0.0.  Let's try to see if we can figure this out.  I've compiled a list of common pitfalls with weather for Graphite here: https://stefanheule.com/graphite/ (scroll down).  Could you see if any of them fix the issue (they should all equally apply to the Obsidian watchface).  It's a little bit of a long shot, but let's try anyway.

Otherwise, can you completely remove Obsidian and reinstall it?

**Comment by WJCFerguson** [comment]
Hi Stefan, thanks for your help.

No joy from the troubleshooting or reintall (via pebble app).  I switched the config to OpenWeatherMap to make sure I'm not hitting any API key issues, but still see nothing.

Other watchfaces are getting weather data, which tends to imply it's not my Android config.  Most puzzling.  Do you have any suggestions for debug - like any logs I can generate?  I have worked through setting up the dev environment (and made a crappy watch face) in the past - if it comes to that I may have to go that way.

Graphite looks great - I like the precipitation graph.  But I'm on a PTR and really like analog and the clean look of Obsidian.

**Comment by stefanheule** [comment]
Alright, lets see if we can get to the bottom of this.  If you have a dev environment, you should be able to get some logs by just viewing the log from your watch using the pebble tool.  You'll need to activate the Pebble Developer connection on your Pebble phone app, and then on your computer you can run `pebble logs --phone <ip-of-the-pebble-dev-server`.  Do that, and then on your watchface change the weather provider (ideally try both the one with the API key, as well as the default one without API key).  If you tell me what the log shows, that would probably give us some clues as to what is going on.

Let me know if anything is unclear.

**Comment by stefanheule** [comment]
And yeah, graphite doesn't even support the PTR, I never figured out a good way to have it look nice on a round display.  Analog faces are much nicer on the PTR :)

**Comment by WJCFerguson** [comment]
Thanks - I'll try to get on this soon, but it'll take a bit of effort and time is tight right now (new job).  I'll report back what I discover.

**Comment by WJCFerguson** [comment]
So on rebooting my phone, the weather is back.  I would swear that I did that during the period I lost the weather, but perhaps not.  So, thanks for your time, and my apologies for wasting it, but it seems that turning it off and turning it on again was where I should have started.

**Comment by stefanheule** [comment]
That's quite alright, I'm glad it's working again.  Good old [turning it off and on again](https://www.youtube.com/watch?v=nn2FB1P_Mn8). ;)

**Comment by WJCFerguson** [comment]
exactly :)
